local millennium = require("millennium")
local ffi = require("ffi")
local logger = require("logger")

ffi.cdef[[
typedef unsigned long DWORD; typedef void* HANDLE; typedef unsigned short WCHAR;
typedef struct { DWORD cb; void* r; void* desktop; void* title; DWORD x,y,xs,ys,xc,yc,fill,flags; unsigned short show,r2; void* rp; HANDLE inH,outH,errH; } SF_STARTUP;
typedef struct { HANDLE process; HANDLE thread; DWORD pid; DWORD tid; } SF_PROCESS;
int MultiByteToWideChar(unsigned int, DWORD, const char*, int, WCHAR*, int);
int CreateProcessW(const WCHAR*, WCHAR*, void*, void*, int, DWORD, void*, const WCHAR*, SF_STARTUP*, SF_PROCESS*);
int CloseHandle(HANDLE); DWORD GetCurrentProcessId(void);
long RegOpenKeyExW(HANDLE, const WCHAR*, DWORD, DWORD, HANDLE*);
long RegQueryValueExW(HANDLE, const WCHAR*, void*, DWORD*, unsigned char*, DWORD*);
long RegCloseKey(HANDLE);
long SbieApi_QueryProcess(HANDLE, WCHAR*, WCHAR*, WCHAR*, DWORD*);
]]
local kernel = ffi.load("kernel32")
local advapi = ffi.load("advapi32")
local state = (os.getenv("LOCALAPPDATA") or "") .. "\\SteamFusion"
local environment = "native"

local function wide(text)
    local count = kernel.MultiByteToWideChar(65001, 0, text, #text, nil, 0)
    local buffer = ffi.new("WCHAR[?]", count + 1)
    kernel.MultiByteToWideChar(65001, 0, text, #text, buffer, count)
    return buffer
end
local function read(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local value = f:read("*a"); f:close(); return value
end

-- Keep serialization in the Windows CLI. No JSON library/version dependency in Lua.
local function cli_path()
    local file = read(state .. "\\cli-path.txt")
    if not file then error("请先运行发布包的 Install.ps1，登记 Windows 控制器路径。") end
    file = file:gsub("[\r\n]+$", "")
    if file:find('["\r\n]') or not file:match("^%a:\\") then error("控制器路径无效") end
    return file
end
local function spawn(args)
    local exe = cli_path()
    local si = ffi.new("SF_STARTUP[1]"); si[0].cb = ffi.sizeof("SF_STARTUP")
    local pi = ffi.new("SF_PROCESS[1]")
    local ok = kernel.CreateProcessW(wide(exe), wide('"' .. exe .. '" ' .. args), nil, nil, 0, 0x08000000, nil, nil, si, pi)
    if ok == 0 then error("启动 SteamFusion CLI 失败") end
    kernel.CloseHandle(pi[0].thread); kernel.CloseHandle(pi[0].process)
    return true
end
local function steam_pid()
    local key = ffi.new("HANDLE[1]")
    local hkcu = ffi.cast("HANDLE", ffi.cast("intptr_t", -2147483647))
    if advapi.RegOpenKeyExW(hkcu, wide("Software\\Valve\\Steam\\ActiveProcess"), 0, 0x20019, key) ~= 0 then return 0 end
    local value = ffi.new("DWORD[1]"); local size = ffi.new("DWORD[1]", 4)
    local result = advapi.RegQueryValueExW(key[0], wide("pid"), nil, nil, ffi.cast("unsigned char*", value), size)
    advapi.RegCloseKey(key[0])
    return result == 0 and tonumber(value[0]) or 0
end

---@ffi
---@return string
function fusion_config()
    local raw = read(state .. "\\plugin-routes.json")
    if not raw then return '{"environment":"' .. environment .. '","games":[]}' end
    -- This file is generated by the app with a fixed environment placeholder.
    return raw:gsub('"__ENVIRONMENT__"', '"' .. environment .. '"')
end

---@ffi
---@param appId number
---@return boolean
function fusion_launch(appId)
    if appId < 1 or appId > 4294967295 or appId ~= math.floor(appId) then error("AppID 无效") end
    return spawn("launch " .. string.format("%.0f", appId))
end

---@ffi
---@param appId number
---@param steamId string
---@return boolean
function fusion_launch_as(appId, steamId)
    if appId < 1 or appId > 4294967295 or appId ~= math.floor(appId) or not steamId:match("^765%d%d%d%d%d%d%d%d%d%d%d%d%d%d$") then error("启动参数无效") end
    return spawn("launch-as " .. string.format("%.0f", appId) .. " " .. steamId)
end

local launch_options_refresh = 0
---@ffi
---@return string
function fusion_launch_options()
    if environment ~= "native" then return "null" end
    if os.time() - launch_options_refresh >= 20 then
        launch_options_refresh = os.time()
        spawn("refresh-launch-options")
    end
    return read(state .. "\\launch-options.json") or "null"
end

---@ffi
---@param appId number
---@return boolean
function fusion_download(appId)
    if appId < 1 or appId > 4294967295 or appId ~= math.floor(appId) then error("AppID 无效") end
    return spawn("download " .. string.format("%.0f", appId))
end

local installation_refresh = 0
---@ffi
---@return string
function fusion_installations()
    if environment ~= "native" then return "null" end
    if os.time() - installation_refresh >= 20 then
        installation_refresh = os.time()
        spawn("refresh-installations")
    end
    return read(state .. "\\installation-index.json") or "null"
end

---@ffi
---@return boolean
function fusion_settings() return spawn("settings") end

---@ffi
---@param steamId string
---@param payload string
---@return boolean
function fusion_catalog(steamId, payload)
    if environment ~= "native" or not steamId:match("^765%d%d%d%d%d%d%d%d%d%d%d%d%d%d$") or #payload > 4194304 then return false end
    local path = state .. "\\catalogs\\" .. steamId .. ".json"
    local f = io.open(path .. ".tmp", "wb")
    if not f then return false end
    f:write(payload); f:close()
    os.remove(path)
    return os.rename(path .. ".tmp", path) ~= nil
end

---@ffi
---@param steamId string
---@param loggedOn boolean
---@return boolean
function fusion_signal(steamId, loggedOn)
    if steamId ~= "" and not steamId:match("^765%d%d%d%d%d%d%d%d%d%d%d%d%d%d$") then return false end
    local pid = steam_pid()
    if pid == 0 then return false end
    local path = state .. "\\signals\\" .. environment .. ".json"
    local f = io.open(path .. ".tmp", "wb")
    if not f then return false end
    f:write(string.format('{"pid":%d,"steamId":"%s","loggedOn":%s,"runningGames":[],"activityKnown":false,"timestamp":%d,"environment":"%s"}',
        pid, steamId, loggedOn and "true" or "false", os.time() * 1000, environment))
    f:close()
    -- Windows rename cannot replace an existing file; a missing sample is treated as Unknown.
    os.remove(path); return os.rename(path .. ".tmp", path) ~= nil
end

local function on_load()
    if ffi.os ~= "Windows" then error("SteamFusion 当前只支持 Windows") end
    local ok, sbie = pcall(ffi.load, "SbieDll")
    if ok then
        local box = ffi.new("WCHAR[34]"); local image = ffi.new("WCHAR[96]"); local sid = ffi.new("WCHAR[96]"); local session = ffi.new("DWORD[1]")
        if sbie.SbieApi_QueryProcess(ffi.cast("HANDLE", kernel.GetCurrentProcessId()), box, image, sid, session) == 0 and box[0] ~= 0 then
            local chars = {}; for i = 0, 32 do if box[i] == 0 then break end; chars[#chars + 1] = string.char(box[i]) end
            local name = table.concat(chars)
            if not name:match("^[A-Za-z][A-Za-z0-9_]*$") then error("不支持的沙盒名") end
            environment = name
        end
    end
    millennium.ready()
    logger:info("SteamFusion environment: " .. environment)
end
return { on_load = on_load, on_unload = function() end }
